uri_folder: /data0/zhangpeng6/qlib/reproduction/mlruns
analysis_folder: /data0/zhangpeng6/qlib/reproduction/analysis
provider_uri: /data0/zhangpeng6/qlib/reproduction/data
pfx_name: REPRO
sfx_name: FROM_SCRATCH
model_name: Linear
dataset_name: Alpha158
stock_pool: csi300
step: 60
rolling_type: custom
predict_dates:
- start: '2026-07-23'
  end: '2026-07-23'
model_filter:
- ^REPRO_
rec_filter:
- ic: 0.001
- icir: 0.001
- rankic: 0.001
- rankicir: 0.001
